spring:
  profiles:
    active: local
  r2dbc:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    url: ${spring.liquibase.url}
    user: ${spring.liquibase.user}
    password: ${spring.liquibase.password}