server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/payment
    username: postgres
    password: 1234
  liquibase:
    url: jdbc:postgresql://localhost:5432/payment
    user: postgres
    password: 1234