spring:
  profiles:
    active: local
---
spring:
  output:
    ansi:
      enabled: always
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:db-init/schema.sql
      data-locations: classpath:db-init/test.sql
logging:
  level:
    org.duhan.webfluxcoroutinepaymentserver: debug
    org.springframework.r2dbc.core: debug
    org.springframework.r2dbc.connection.init: debug
    org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler: off
    org.springframework.web.HttpLogging: off
