package org.duhan.webfluxcoroutinepaymentserver.domain.order.mock

import org.duhan.webfluxcoroutinepaymentserver.domain.order.model.Order
import org.duhan.webfluxcoroutinepaymentserver.domain.order.port.OrderRepository

class FakeOrderRepository : OrderRepository {
    private var autoGeneratedId: Long = 0
    private val data: MutableList<Order> = mutableListOf()

    override suspend fun save(order: Order): Order {
        if (order.id == null || order.id == 0L) {
            val newOrder =
                Order(
                    id = ++autoGeneratedId,
                    userId = order.userId,
                    description = order.description,
                    amount = order.amount,
                    pgOrderId = order.pgOrderId,
                    pgKey = order.pgKey,
                    pgStatus = order.pgStatus,
                    pgRetryCount = order.pgRetryCount,
                    createdAt = order.createdAt,
                    updatedAt = order.updatedAt,
                )
            data.add(newOrder)
            return newOrder
        } else {
            data.removeIf { it.id == order.id }
            data.add(order)
            return order
        }
    }
}
